### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#10]
Hi,

It could be great to have some contribution guidelines (contrib.md, role_skeleton for ansible-galaxy)

Skeleton example (you just need to provide a role directory template somewhere in this repo) : https://github.com/cjsteel/galaxy-role-skeleton
Usage : ansible-galaxy init --role-skeleton=<skeleton_dir> <role_name>

**Comment by johnnykeats** [comment]
Hi!

Thanks for the feedback.
I tried to create a contribution file. Hope this is what you are expecting. I will try to "make it live" as we encounter new situations.

Regarding Skeleton for Ansible Galaxy, this is is something I am not familiar with, I will let Oxedions work on this :blush:

**Comment by oxedions** [comment]
Hello,

Thank you JK for the contrib file ;-)

So for what I understand, we should provide a skeleton of our roles for an usage in the Ansible Galaxy. Could be a good opportunity to comply with what is already done in the Ansible world.

The tree generated with the ansible-galaxy command contains much more folders than what we have today, and generated a readme in MD, while we rely on RST for the documentation. I need to check this.

@bouriquet15 , do you know if in this skeleton I need to force things like the license ? Sorry, I am not very used to Ansible Galaxy :-)

Best regards

Ox

**Comment by oxedions** [comment]
No answers, so closing for now.
