### ISSUE TITLE
Create online repository and online documentation

### ISSUE THREAD

**Issue by oxedions** [oxedions/bluebanquise#12]
Need to build all packages for 1.0, i.e. Centos 7 packages for now.

Also need to add online documentation, and remove build directory from git base.

**Comment by johnnykeats** [comment]
Can you redeploy Raphael system ? Then provide me credentials, so I setup this :-)

**Comment by oxedions** [comment]
Hello Johnny,

Server has been reinstalled, I will send you credentials.

We will have documentation and repo inside. Let's structure it exactly the same way than repositories in the stack itself.

Ox

**Comment by oxedions** [comment]
Hello Johnny,

Server is up and running, hardening is done. I am uploading repo.

Once doc is ok on your side, we can close this issue :-)

Ox

**Comment by oxedions** [comment]
Done, at bluebanquise.com
