### ISSUE TITLE
Ensure multi arch and multi distribs works fine

### ISSUE THREAD

**Issue by oxedions** [oxedions/bluebanquise#16]
Tumulus cluster is multi arch (arm64 and x86_64) and also multi distribs.

Check the stacks handle this properly.

**Comment by johnnykeats** [comment]
Found issue on ipxe/dhcp, roms are not arch related, and same for ipxe script.

We need to rely on that:
https://ipxe.org/cfg/platform
https://ipxe.org/cfg/buildarch

**Comment by oxedions** [comment]
Hello Johnny,

So we could create x86_64/ and arm64/ folders for tftp. Would it be interesting to split also EFI and legacy into folders ?

Ox

**Comment by oxedions** [comment]
Latest commit works for me.

Just need to add grub shell in menu.ipxe.

Ox

**Comment by oxedions** [comment]
Tested and ok. RPM also ok.
So far no issues.

Close.
