### ISSUE TITLE
Missing "tagging convention" in contribution guidelines

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#19]
Hi
It could be great to have tag convention (a simple list of standard tags you are using) in CONTRIBUTING file.

**Comment by bouriquet15** [comment]
Tag convention suggestion :
- install : for package module
- template : for template/lineinfile modules (looks like you already use this one, but it is not fully implemented in all roles
- service : force service/systemd module

**Comment by oxedions** [comment]
I can only agree, these tags are vital for diskless elements or just to speedup updates of configuration.

Do you think "install" is better than "package" for packages tag ?

Ox

**Comment by bouriquet15** [comment]
Some of my use cases :
- install tag : in post installation with --check -t install,role_name to check installed packages
- template tag : in post install too with --check --diff to check templates/lines before applying
- service tag : mainly with --skip-tags to disable critical services (re)starting

Feel free to adapt the name of theses tags and/or add more tags, i do not have any preference between "install" vs "package", but i prefer "template" than "templates" ;).

**Comment by oxedions** [comment]
Hello @bouriquet15 ,

My apologies for the delay.

Ok, I will include many tags in 1.2.0 branch, and take this opportunity to clean some "dev" tags.

Ox

**Comment by bouriquet15** [comment]
Following tags have been implemented in issue https://github.com/oxedions/bluebanquise/issues/32 :
* package
* template
* service

**Comment by oxedions** [comment]
Closing because done in another (#32 )
