### ISSUE TITLE
RHEL 8 support

### ISSUE THREAD

**Issue by johnnykeats** [oxedions/bluebanquise#2]
Yo Ox,

As discussed, I will have a look on how to integrate RHEL 8 into BB.
Can you give me the rights, and create the branch for my devs ?
Thanks

JK

**Comment by oxedions** [comment]
Hello JK !

Yes, let me do that :-)
Thanks for taking care of this part, too much to handle.

Cheers
Ox

**Comment by johnnykeats** [comment]
No probs.

Thanks for the branch.

JK

**Comment by johnnykeats** [comment]
So as a report, I got these issues:
https://github.com/ansible/ansible/issues/48055
https://github.com/ansible/ansible/pull/48870

I also add to update atftp code, and patch clustershell spec.

I cleaned your ipxe spec file.

But dude, you changed too much files positions, merge is going to be a mess... -_-'

**Comment by oxedions** [comment]
Yes, sorry about that :-p

I needed to clean things. Can you push your current work, so I can check it ? Seems you did a lot.

**Comment by johnnykeats** [comment]
Done, have a look :-)

**Comment by oxedions** [comment]
Just perfect, many thanks.

Didn't thought so much changes in RHEL 8.

**Comment by oxedions** [comment]
I think you are done. Lets merge, and clean all the current work so we can release v1.

**Comment by johnnykeats** [comment]
OK. Remember the NIC role cannot work with current Ansible, due to bug:
https://github.com/ansible/ansible/issues/48055

I will work on documentation :)

**Comment by oxedions** [comment]
I am cleaning the whole commits to remove all the sources (ipxe, etc) so repo is light.

**Comment by oxedions** [comment]
Merged. Thanks !
