### ISSUE TITLE
Missing "}" in conman role

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#20]
https://github.com/oxedions/bluebanquise/blob/48057e5f6173233f9799f9cf1b141600791bf2e2/roles/core/conman/tasks/main.yml#L5

**Comment by bouriquet15** [comment]
PR submitted : https://github.com/oxedions/bluebanquise/pull/21

**Comment by oxedions** [comment]
Corrected by merging PR.

Thanks for the issue.

Ox
