### ISSUE TITLE
"equipment_naming" not taken by ipxe templates

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#23]
Hi,

The internal var "equipment_naming is not taken by the pxe_stack role.

PR submitted for RH/CentOS part : https://github.com/oxedions/bluebanquise/pull/22

This correction should be applied on other distributions

**Comment by oxedions** [comment]
Thanks for this fix.

I will solve this same issue on ubuntu and opensuse templates.

Will keep this issue open until its done.

Ox

**Comment by oxedions** [comment]
Hello @bouriquet15 ,

Based on your PR that simplified templating for iPXE files, I redesigned the whole iPXE chain process, to handle easily diskless and other boot modes.

You can have a look inside branch 1.2.0, in pxe_stack role.

Many thanks for your initial idea ;-)

**Comment by oxedions** [comment]
Hello @bouriquet15 ,

Since all of this has been rewamped in branch 1.2.0, I will close this issue.

Ox
