### ISSUE TITLE
"equipment_naming" in pxe_stack role task

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#25]
Missing equipment_naming support in pxe_stack task
When condition simplification for RH / CentOS test

PR submitted : https://github.com/oxedions/bluebanquise/pull/24

**Comment by oxedions** [comment]
Hello,

Nice catch. There probably is same issues with iceberg naming, I will check this for the 1.1.1 release.

Many thanks for this PR ;-)

Ox
