### ISSUE TITLE
Improve IPXE ROM robustness

### ISSUE THREAD

**Issue by bouriquet** [oxedions/bluebanquise#26]
Hi,

Can you provide a more reliable IPXE (mainly for the DHCP part) ? It works perfectly with good switches, but when it comes to old switches, the interface configuration command hangs out and timeout after 5 retries.

File : bluebanquise_standard.ipxe

Command to be changed : 
ifconf --configurator dhcp || shell

Exemple provided by the IPXE website : 
:retry
ifconf --configurator dhcp || goto retry

or 

:retry
ifconf -c dhcp && isset ${filename} || goto retry

**Comment by oxedions** [comment]
Hello again,

Thank you for asking this feature.

I can do that. Assuming you are using the iPXE rom, it means you got the DHCP the first time, so waiting for the link to come back is something logical. I already faced this kind of issue with a customer one time.

I will update the ipxe rpm with this new one, and add it into the dhcp role.

Keep you in touch once it is done ;-)

Ox

**Comment by oxedions** [comment]
Added into https://github.com/oxedions/bluebanquise/commit/d67f5e95e1b669c144dcfadf79c74809c9702955

I need to rebuild the ipxe rpm, may take some time...

Ox

**Comment by oxedions** [comment]
Images are built, and available in latest rpms.

Closing.

Ben
