### ISSUE TITLE
Remove python scripts from templates

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#27]
Hi,

I think python scripts (bootset) code should not be include in Ansible templates. 

Moving this code to a more standard path and making the code "static" (by declaring your CLI in a setup.py file and remove sources from role templates) could be a great enhancement.

Configuration of the bootset executable can be done through an external configuration file (let's say /etc/bootset/bootset.conf) and templated by Ansible.

**Comment by oxedions** [comment]
Hello @bouriquet15 

I agree with this.

I will first do the external configuration file part. However could you be more specific regarding the setup.py ? I though of putting the file in the role/files folder to do a simple copy in the task, but what you propose is to put the bootset file into an rpm ?

Ox

**Comment by bouriquet15** [comment]
Hi @oxedions,

Here is a sample project showing how to package a python project and describing all required fields in the setup.py file : https://github.com/pypa/sampleproject

And the associated documentation : https://packaging.python.org/tutorials/packaging-projects/

Theses tutorials are the pythonic way to package your scripts.
For RPM building, you gonna need to add another extra layer (Makefile + SPEC), you can check the Ansible project to see how they organized the repository to build multi distrib packages (but that's really overkilled and hard to understand in your case i think)

Note that with a good organization, you can do only one project for all your python scripts (bootset, diskless?, ...) and declare in this file multiple CLI commands (a good example is also the Ansible project which provide in the same repository multiple binaries : ansible/ansible-inventory/ansible-playbook ...)

**Comment by oxedions** [comment]
Hello @bouriquet15 

Many thanks for all these information. I will consider all of this as I will work on packaging soon.

See last commit, bootset is no more a template :-)

Closing this issue regarding bootset.

Ox
