### ISSUE TITLE
failed restart DHCP with opt82 option tempate

### ISSUE THREAD

**Issue by hmeAtos** [oxedions/bluebanquise#29]
Error '_pool declared outside of network_', this error is not explicit !

The real issue is in /etc/dhcp/dhcpd.{network}.conf
we can't define a pool in a group

**Comment by oxedions** [comment]
Dear @hmeAtos ,

Thank you for this issue.

I will rework the whole advanced dhcp, as opt82 match hack does not seems to accept to be in groups.
I will consider sys admin using advanced dhcp knows what he/she is doing, and so rely only on equipment_profiles to define the iPXE rom to be used.

Branchs 1.1.1 will get the fix soon :-) Note that this will need a modification in the inventory, so an inventory structure breaking fix. This will be notified in the commit by the ! after the Fix tag.

Kind regards

Ox

**Comment by oxedions** [comment]
Dear @hmeAtos ,

Can you check the latest fix in 1.1.1 branch regarding advanced dhcp server ?

I adapted inventory, please check group_vars/all/all_equipments/equipment_profile.yml for new parameters to take into account: ipxe_driver, ipxe_platform, and hardware:cpu:architecture.

Ox

**Comment by oxedions** [comment]
Closing because fixed.
