### ISSUE TITLE
adding a BMC entry with option_match in inventory doesn't work 

### ISSUE THREAD

**Issue by hmeAtos** [oxedions/bluebanquise#30]
Hi,
i find a new issue.
When I want to add a BMC entry with option82 match, the entry in dhcp file isn't added.
On the other hand, the entry with mac works.

```
          bmc:
            name: pm0-bmc05
            #mac: 08:00:27:0d:f8:b2
            option_match: |
              substring (option agent.remote-id, 0 , 64) = "0"
              and option agent.circuit-id = 01:00:10
              and (substring(option vendor-class-identifier, 0, 10) = "XXXX S BMC")
            ip4: 10.0.0.106
            network: ice1-1
```
Kind regards,

**Comment by oxedions** [comment]
Hello,

Fixed in https://github.com/oxedions/bluebanquise/commit/0931f6ca46dac6cebb262b81a2572b0947bdf777

My apologies for this bady copy/past :-p

Ox

**Comment by hmeAtos** [comment]
great!
Thanks
