### ISSUE TITLE
Improve quality, add services enabling/disabling variable

### ISSUE THREAD

**Issue by bouriquet15** [oxedions/bluebanquise#32]
Hi,

i submitted a PR (see https://github.com/oxedions/bluebanquise/pull/31) containing the following changes :

**Major changes :**
* Add boolean to disable all services (HA)
* Implement tags + tag uniformisation (package, template, service)
* Implement handlers

**Minor changes :**
* Use new package module syntax (using list in name instead of loops)
* Replace some "with_X" by loop
* Minor fixes

The issue https://github.com/oxedions/bluebanquise/issues/19 can also be updated (contribution guidelines should be updated before closing)

**Comment by oxedions** [comment]
Dear @bouriquet15 

Many thanks.

Could you also add a way to disable services start/restart/stop ? So absolutely no services managements.

If you need, I can do it on my side.

Ox

**Comment by bouriquet15** [comment]
Hey,

PR updated with service state handling + some minor fixes

**Comment by oxedions** [comment]
Hello,

Many thanks.
Reviewed, and ok.

**Comment by oxedions** [comment]
And release 1.1.1 is out ;-)

Many thanks. I hope github will add you as contributor automatically, we will see soon.
