### ISSUE TITLE
iPXE os deployment is not working on RHEL 7 (and probably on Centos 7)

### ISSUE THREAD

**Issue by gavillom** [oxedions/bluebanquise#39]
Hi,

iPXE os deployment is not working on RHEL 7. in fact, inst.repo URL point to a BaseOS folder that is existent in Redhat 8 but not in Redhat 7. It causes pxe installation failure.

Mathis

**Comment by gavillom** [comment]
Proposed PR: #40

**Comment by oxedions** [comment]
Hello @gavillom 

See comment in the PR.

Many thanks !

Ben
