### ISSUE TITLE
Improve roles:  'repositories_client' 'repositories_server'

### ISSUE THREAD

**Issue by hmeAtos** [oxedions/bluebanquise#41]
Hi,

It is possible to add a feature allowing to access an external repos ?
For exemple : EPEL, Erratas, or others 

```
internal_repo:
 - os
 - repo1

external_repo:
  - { name: epel, url: ... }
  - { name: errata, url: ... }
```

Best regards,

**Comment by bouriquet** [comment]
https://github.com/oxedions/bluebanquise/pull/44

**Comment by oxedions** [comment]
Hello @hmeAtos 

Many thanks for this FR.

@bouriquet Propose a PR, merged. However, I let this feature request open, as I am not satisfied with current naming convention.

Ben

**Comment by oxedions** [comment]
Fixed by https://github.com/oxedions/bluebanquise/commit/d60214be34d6083c7b29922e4ddb8d9aaf745672
