### ISSUE TITLE
bootset refactoring

### ISSUE THREAD

**Issue by bouriquet** [oxedions/bluebanquise#43]
Hi @oxedions,

Just submitted a bootset refactoring PR here : https://github.com/oxedions/bluebanquise/pull/42

It can be improved, but i think that's a better base for improvment.

TODO :

- OO class
- Add error handling
- More flexibility (we should be able to develop additionnal plugins to add more boot methods)
- Use logging lib instead of print

**Comment by oxedions** [comment]
Hello,

Many thanks for the associated PR.

Could you explain me why it is better to use '   '.format(), on multiple lines, instead of doing a big myval = """ my text on multiple lines """.format() ?

I found the second method easier to read by users.

Ben

**Comment by bouriquet** [comment]
Hi,

That's not better, just a personal choice for this correction. 

Since you cannot indent your text when using """ ... """ on multiple lines, i found it was more readable to use a set ('','',...) and indent this portion of code. 

You still can move the .format at the end of the line if you think it is more readable that a "by line" format

**Comment by oxedions** [comment]
I updated the script :
```
#        return yaml.load(f, Loader=yaml.FullLoader) ## Waiting for PyYaml 5.1
        return yaml.load(f)
```
In RHEL 8, I have an issue with PyYaml version :-(

Ben

**Comment by oxedions** [comment]
As discussed, done for now.
