### ISSUE TITLE
EFI not managed

### ISSUE THREAD

**Issue by johnnykeats** [oxedions/bluebanquise#5]
Yo Ox,

I found EFI is baldy managed: sanboot in menu.ipxe do not work in EFI, and iPXE usb and iso images do not contains EFI part.

OK if I take care of that ? The CINES SMP node is in EFI and this is broken this way.

**Comment by johnnykeats** [comment]
I will create a dedicated branch.

**Comment by johnnykeats** [comment]
Added EFI, tested on the SMP node, all ok.
In the futur, we may need to add RedHat/Ubuntu/OpenSuse grub.cfg file into the discovery script.

**Comment by oxedions** [comment]
Hello JK,

Ok, I see how you made it. That's smart, I like it.
So now I am able to boot even VirtualBox in EFI using your ISO 👍
