### ISSUE TITLE
Need script and directory tags in pxe_stack role

### ISSUE THREAD

**Issue by jpm38** [oxedions/bluebanquise#59]
When deploying services like dhcp, tftp, http, dns etc. inside containers running on various bare metal nodes, we used the ansible "chroot" connector to generate the configuration files on a shared file system mounted on all nodes. 
We want to use the standard roles (dhcp, dns, pxe_stack ...) for that purpose, but we do NOT want to start the services on the bare metal management node. So we use the template tag , but we need also for pxe_stack role to create the output directories and to copy the bootswitch cgi script. So, a directory and a script tag are needed for that.

**Comment by oxedions** [comment]
Dear @jpm38 ,

Thank you for this proposal. I agree it would be a good feature.

Could you propose a PR based on branch 1.2.0 ?

Many thanks !

Ox

**Comment by jpm38** [comment]
Dear @oxedions 

Sounds goot to me.

JPM

**Comment by actatux** [comment]
Could you achieve the same behavior (don't start services) with --skip-tags "service"?

**Comment by jpm38** [comment]
I've tested your proposal adding also the skip of "package":
--skip-tags package,service

and it does the trick.

thanks

**Comment by actatux** [comment]
Can we close then?

**Comment by jpm38** [comment]
yes, sure

**Comment by oxedions** [comment]
Closing.
