### ISSUE TITLE
Need to have 2 disctinct services for tftp and http in pxe chain boot

### ISSUE THREAD

**Issue by jpm38** [oxedions/bluebanquise#60]
Bluebanquise stack uses the same IP address in pxe chain boot for tftp service and http service: The pxe_ip variable in network definition.
networks:
  ice1-1:
    subnet: 10.10.0.0
    prefix: 16
    netmask: 255.255.0.0
    broadcast: 10.10.255.255
    dhcp_unknown_range: 10.10.254.1 10.10.254.254
    gateway: 10.10.255.254
    is_in_dhcp: true
    is_in_dns: true
    services_ip:
      pxe_ip: 10.10.0.1

This is working fine when services are running on the same host/VM/container and so exposing the same IP address for both services.
When deploying services like dhcp, tftp, http, dns etc. inside containers running on various bare metal nodes, orchestrated bu Kubernetes, we have a service IP address per service. For that reason, we need to have a pxe chain boot solution for which we can configure a tftp_ip address and a pxe_ip address for respectively access to TFTP server and HTTP server.

**Comment by oxedions** [comment]
Dear @jpm38 ,

I understand your need.

The PXE chain was designed to be as simple as possible for debugging, as I found PXE part is always the trickiest part.

However, having the ability to split these 2 ip is understandable.

I can propose you the following way, only for advanced_dhcp_server role:

If in network ice1-1 for example, the service pxe_http_ip is set (assuming here 10.10.77.1), then dhcp template will add in the ice1-1 subnet:

`option root-path "10.10.77.1";`

And then, in the embed script of the rom, there would be:

`isset ${root-path} && set next-server ${root-path}`

This way, next-server ip would be override by this new ip.

I know root-path was not design for an ip, but for an iSCSI target. However, the probability someone use the BlueBanquise iPXE rom for iSCSI targets is very very low...

Would this be a good solution for you ?

Ox

**Comment by jpm38** [comment]
Dear @oxedions 

Your proposal looks good to me and fit exactly our needs.
Can I hope to have this feature in 1.2 ?
Many thanks

JPM

**Comment by oxedions** [comment]
Dear @jpm38 ,

@actatux PR provided a solution.

I will rebuild new roms and you will be able to benefit from it, in 1.2.0 version :-)

Ben
