### ISSUE TITLE
How to organize tasks when mixed ditros

### ISSUE THREAD

**Issue by johnnykeats** [oxedions/bluebanquise#7]
Yo Ox,

I was wondering, how should we organize tasks when dealing with multiple distros ?

You know, with centos_7.yml, ubuntu_18.yml etc files, because for some tasks packages only is not enough :-( you have to deal with paths or services also...

**Comment by oxedions** [comment]
Hello Johnny,

Sorry for the (big) delay.

I think we can create some main file with all tasks using vars from roles, and then only create specific tasks files when we have actions for only one OS.

I will also work on replacing old with_items by loops. If you can also use these now :-)

Cluster should be up soon, are you ready on Ubuntu side ?

Ox

**Comment by johnnykeats** [comment]
Always late man, as usual :-p

Ok, thanks. I will do it this way, as we discuss yesterday. I am almost done on Ubuntu, just some strange very long hang during OS install, don't know what is going on, no messages from installer. But after 10min install goes on.

Do you know when Tumulus cluster will be up?

**Comment by johnnykeats** [comment]
Yo Ox,

I could reach management. Wasn't expecting aarch64 system, I will rebuild packages for this platform. So mixed aarch64/x86_64 cluster, with Ubuntu and Centos systems. Lot of fun in perspective :heart_eyes:

I agree with roles, let's split them. Its boring to handle these big CORE/ADDON stuff. Can you do it?

**Comment by oxedions** [comment]
Hello Johnny,

OK, I will do that. I will also update ansible.cfg file to handle these new PATH, and same for the documentation.

Ox

**Comment by oxedions** [comment]
Hello Johnny,

Done !

Ox
