### ISSUE TITLE
 Need the dns server to listen and allow query on all networks

### ISSUE THREAD

**Issue by loar38** [oxedions/bluebanquise#94]
In a kubernetes context, the DNS server is started in a container and only knows the kubernetes network (not managed by bluebanquise but by kubernetes)
In this case, we must delete the listen-on and allow_query section and keep the default behavior to be able to function

for example

```
cat /etc/ansible/kubernetes-dns.patch
 
--- roles/core/dns_server/templates/named.conf.j2.bb    2020-02-05 14:51:21.871668303 +0100
+++ roles/core/dns_server/templates/named.conf.j2       2020-02-05 14:52:41.327668303 +0100
@@ -12,14 +12,14 @@
 {% set main_ntw = (ntw | first | join | trim) %}
 
 options {
-  listen-on port 53 {
-    127.0.0.1;
-{% for network in (networks | select('match',(j2_current_iceberg_network+'-[0-9]+')) | list | unique | sort) %}
-{% if networks[network]['is_in_dns'] is defined and networks[network]['is_in_dns'] == true %}
-    {{networks[network]['services_ip']['dns_ip']}};
-{% endif %}
-{% endfor %}
-  };
+  #listen-on port 53 {
+    #127.0.0.1;
+#{% for network in (networks | select('match',(j2_current_iceberg_network+'-[0-9]+')) | list | unique | sort) %}
+#{% if networks[network]['is_in_dns'] is defined and networks[network]['is_in_dns'] == true %}
+    #{{networks[network]['services_ip']['dns_ip']}};
+#{% endif %}
+#{% endfor %}
+  #};
 
   listen-on-v6 port 53 { ::1; };
   directory    "/var/named";
@@ -27,14 +27,14 @@ options {
   statistics-file "/var/named/data/named_stats.txt";
   memstatistics-file "/var/named/data/named_mem_stats.txt";
 
-  allow-query {
-    localhost;
-{% for network in (networks | select('match',(j2_current_iceberg_network+'-[0-9]+')) | list | unique | sort) %}
-{% if (networks[network]['is_in_dns'] is defined and not none) and (networks[network]['is_in_dns'] == true) %}
-    {{networks[network]['subnet']}}/{{networks[network]['prefix']}};
-{% endif %}
-{% endfor %}
-  };
+  #allow-query {
+    #localhost;
+#{% for network in (networks | select('match',(j2_current_iceberg_network+'-[0-9]+')) | list | unique | sort) %}
+#{% if (networks[network]['is_in_dns'] is defined and not none) and (networks[network]['is_in_dns'] == true) %}
+    #{{networks[network]['subnet']}}/{{networks[network]['prefix']}};
+#{% endif %}
+#{% endfor %}
+  #};
 
 {% if external_dns.dns_server is defined and not none and external_dns.dns_server %}
   forwarders {
```

**Comment by actatux** [comment]
Hello @loar38 ,

Would adding the k8s network configuration to your inventory be an acceptable solution?

We can still add a tunable to toggle the use of `listen-on` and `allow-query`, but listening on all interfaces and answering to any request might have undesirable side-effects one need to understand before disabling those options.

**Comment by loar38** [comment]
Hello @actatux ,
After several tests with an additional network and fake nic on this network, it seems ok for chrony, dns and dhcp but we found a bug on the advance_nic role.
As the IP on the host is managed by kubernetes we can't set an IP for the new nic and then the role generate a wrong ifcfg file for the fake nic.
An other remark is that for the dns as we don't know in advance the IP of the container, we set a subnet as dns_ip
example:
```
networks:
  ice1-k8s:
    subnet: 192.168.0.0
    netmask: 255.255.0.0
    prefix: 16
    is_in_dhcp: false
    is_in_dns: true
    services_ip:
      dns_ip: 192.168.0.0/16
```
If you are ok, I will close this issue and opena new on for the nic role.
Regards
Laurent

**Comment by actatux** [comment]
Hello @loar38 ,

There is no `advance_nic` role, do you mean `nic`?

About your dns issue, I'm not familiar with k8s, but I find it surprising you cannot set an IP for the service, especially dns. Any other service can change its IP dynamically, all you would have to do is to update the map and reload the dns configuration. But for dns, if your IP should be set randomly, how would you configure the nameserver in /etc/resolv.conf?

That would not be an issue in an ephemeral HPC instance in the cloud, but for on-premise configuration, you should definitely consider using static IP address for your dns servers.

**Comment by loar38** [comment]
Hello @actatux ,
It seems that the advance_nic role has be moved to the nic role en 1.2 version.
Thank you for your remark 
You have right, all services have an external IP to be adressed by equipement outside the k8s internal network.
The IP service (external) for dns are static and not allocated by kubernetes 
But pods knows only the k8s internal network.
This is why the service need to allow or listen the k8s internal network.
When I talk about IP managed by k8s, I talk about the internal IP for the Pods not the external IP of the service.
