### ISSUE TITLE
Bluebanquise roles should support chroot ansible_connection type

### ISSUE THREAD

**Issue by gavillom** [oxedions/bluebanquise#95]
Hey,

From several weeks now, we're using the amazing Bluebanquise roles to manage our cluster and most of all to customize our overlayfs diskless images. 
That allow us to have diskfull and diskless system configured on the same way, which really ease the way of managing clusters.

Some roles are using "service" Ansible task that do not work very well when using chroot ansible connection plugin. In fact it makes services starting in the diskless image chroot where we only expect the service to be enabled. And that can cause some troubles on the node we're generating this diskless.

That would be amazing if Bluebanquise core roles could take care of this need (and I think we need to think about this a little).

Mathis

**Comment by oxedions** [comment]
Dear @gavillom 

Thank you for this issue.

Did you check the general settings?

https://github.com/oxedions/bluebanquise/blob/master/resources/examples/simple_cluster/inventory/group_vars/all/general_settings/general.yml

You can disable here services (enable and/or start).

Maybe it will be enough to solve your problem ? If not, then indeed there is an issue :-)

With my best regards

Ben

**Comment by actatux** [comment]
Hello Mathis,

The solution provided by @oxedions should answer your need. While discussing the issue, we noticed some roles don't support the 2 parameters `enable_services` and `start_services`.
This should be fixed with PR #99. Please give a try and provide a feedback.
